USE Colleges
GO
SELECT A.INSTNM, A.CITY, A.STABBR, A.MAIN, B.CREDDESC, B.CIPDESC, B.MD_EARN_WNE, B.DEBTMEDIAN, C.ADM_RATE, D.SATMTMID, D.SATVRMID, D.SATWRMID, D.SAT_AVG, D.SAT_AVG_ALL, E.NPT4_PUB, E.NPT4_PRIV, E.NPT45_PUB, E.NPT45_PRIV
FROM dbo.Institution AS A
INNER JOIN dbo.Field_Study_Earnings AS B
ON A.UNITID = B.UNITID
INNER JOIN dbo.University_Year AS C
ON A.UNITID = C.UNITID
INNER JOIN dbo.SAT_ACT AS D
ON A.UNITID = D.UNITID
INNER JOIN dbo.Cost AS E
ON A.UNITID = E.UNITID
WHERE B.MD_EARN_WNE IS NOT NULL AND C.School_Year = '2018_19' AND D.School_Year = '2018_19' AND E.School_Year = '2018_19' AND B.CREDDESC LIKE 'Bache%'
ORDER BY B.MD_EARN_WNE DESC

-- Count of Bachelor degrees by Field of study for data wirh earnings


-- Create a view for box plot in CCRS .. just counts higher than 200
-- Top 28 Degrees by Number of instituations that offer it

SELECT A.[CIPDESC],A.[OPEID6] , A.[UNITID] , A.[INSTNM], A.[MD_EARN_WNE]
FROM [dbo].[Field_Study_Earnings] AS A
INNER JOIN (SELECT TOP 28 [CIPDESC], COUNT([INSTNM]) AS Count_of_Inst
FROM [dbo].[Field_Study_Earnings]
WHERE [CREDDESC] LIKE 'Bache%' AND MD_EARN_WNE IS NOT NULL
GROUP BY [CIPDESC]
ORDER BY Count_of_Inst DESC) AS C
ON A.CIPDESC  = C.CIPDESC
WHERE A.[MD_EARN_WNE] IS NOT NULL AND A.[CREDDESC] LIKE 'Bache%'




--Santa Fe UNIT ID 137096

SELECT A.INSTNM, A.CITY, A.STABBR, A.MAIN, B.CREDDESC, B.CIPDESC, B.MD_EARN_WNE, B.DEBTMEDIAN, C.ADM_RATE, D.SATMTMID, D.SATVRMID, D.SATWRMID, D.SAT_AVG, D.SAT_AVG_ALL, E.NPT4_PUB, E.NPT4_PRIV, E.NPT45_PUB, E.NPT45_PRIV
FROM dbo.Institution AS A
INNER JOIN dbo.Field_Study_Earnings AS B
ON A.UNITID = B.UNITID
INNER JOIN dbo.University_Year AS C
ON A.UNITID = C.UNITID
INNER JOIN dbo.SAT_ACT AS D
ON A.UNITID = D.UNITID
INNER JOIN dbo.Cost AS E
ON A.UNITID = E.UNITID
WHERE A.UNITID = 137096 AND C.School_Year = '2018_19' AND D.School_Year = '2018_19' AND E.School_Year = '2018_19'
ORDER BY B.MD_EARN_WNE DESC


-- University of Florida 134130 and Bachelor

SELECT A.INSTNM, A.CITY, A.STABBR, A.MAIN, B.CREDDESC, B.CIPDESC, B.MD_EARN_WNE, B.DEBTMEDIAN, C.ADM_RATE, D.SATMTMID, D.SATVRMID, D.SATWRMID, D.SAT_AVG, D.SAT_AVG_ALL, E.NPT4_PUB, E.NPT4_PRIV, E.NPT45_PUB, E.NPT45_PRIV
FROM dbo.Institution AS A
INNER JOIN dbo.Field_Study_Earnings AS B
ON A.UNITID = B.UNITID
INNER JOIN dbo.University_Year AS C
ON A.UNITID = C.UNITID
INNER JOIN dbo.SAT_ACT AS D
ON A.UNITID = D.UNITID
INNER JOIN dbo.Cost AS E
ON A.UNITID = E.UNITID
WHERE A.UNITID = 134130 AND C.School_Year = '2018_19' AND D.School_Year = '2018_19' AND E.School_Year = '2018_19' AND B.CREDDESC LIKE 'Bachel%'
ORDER BY B.MD_EARN_WNE DESC

-- FSU 134097 Bachelors

SELECT A.INSTNM, A.CITY, A.STABBR, A.MAIN, B.CREDDESC, B.CIPDESC, B.MD_EARN_WNE, B.DEBTMEDIAN, C.ADM_RATE, D.SATMTMID, D.SATVRMID, D.SATWRMID, D.SAT_AVG, D.SAT_AVG_ALL, E.NPT4_PUB, E.NPT4_PRIV, E.NPT45_PUB, E.NPT45_PRIV
FROM dbo.Institution AS A
INNER JOIN dbo.Field_Study_Earnings AS B
ON A.UNITID = B.UNITID
INNER JOIN dbo.University_Year AS C
ON A.UNITID = C.UNITID
INNER JOIN dbo.SAT_ACT AS D
ON A.UNITID = D.UNITID
INNER JOIN dbo.Cost AS E
ON A.UNITID = E.UNITID
WHERE A.UNITID = 134097 AND C.School_Year = '2018_19' AND D.School_Year = '2018_19' AND E.School_Year = '2018_19' AND B.CREDDESC LIKE 'Bachel%'
ORDER BY B.MD_EARN_WNE DESC

-- UCF 132903

SELECT A.INSTNM, A.CITY, A.STABBR, A.MAIN, B.CREDDESC, B.CIPDESC, B.MD_EARN_WNE, B.DEBTMEDIAN, C.ADM_RATE, D.SATMTMID, D.SATVRMID, D.SATWRMID, D.SAT_AVG, D.SAT_AVG_ALL, E.NPT4_PUB, E.NPT4_PRIV, E.NPT45_PUB, E.NPT45_PRIV
FROM dbo.Institution AS A
INNER JOIN dbo.Field_Study_Earnings AS B
ON A.UNITID = B.UNITID
INNER JOIN dbo.University_Year AS C
ON A.UNITID = C.UNITID
INNER JOIN dbo.SAT_ACT AS D
ON A.UNITID = D.UNITID
INNER JOIN dbo.Cost AS E
ON A.UNITID = E.UNITID
WHERE A.UNITID = 132903 AND C.School_Year = '2018_19' AND D.School_Year = '2018_19' AND E.School_Year = '2018_19' AND B.CREDDESC LIKE 'Bachel%'
ORDER BY B.MD_EARN_WNE DESC

--USF 137351 Bachelor

SELECT A.INSTNM, A.CITY, A.STABBR, A.MAIN, B.CREDDESC, B.CIPDESC, B.MD_EARN_WNE, B.DEBTMEDIAN, C.ADM_RATE, D.SATMTMID, D.SATVRMID, D.SATWRMID, D.SAT_AVG, D.SAT_AVG_ALL, E.NPT4_PUB, E.NPT4_PRIV, E.NPT45_PUB, E.NPT45_PRIV
FROM dbo.Institution AS A
INNER JOIN dbo.Field_Study_Earnings AS B
ON A.UNITID = B.UNITID
INNER JOIN dbo.University_Year AS C
ON A.UNITID = C.UNITID
INNER JOIN dbo.SAT_ACT AS D
ON A.UNITID = D.UNITID
INNER JOIN dbo.Cost AS E
ON A.UNITID = E.UNITID
WHERE A.UNITID = 137351 AND C.School_Year = '2018_19' AND D.School_Year = '2018_19' AND E.School_Year = '2018_19' AND B.CREDDESC LIKE 'Bachel%'
ORDER BY B.MD_EARN_WNE DESC

-- FLORIDA Bachelor

SELECT A.INSTNM, A.CITY, A.STABBR, A.MAIN, B.CREDDESC, B.CIPDESC, B.MD_EARN_WNE, B.DEBTMEDIAN, C.ADM_RATE, D.SATMTMID, D.SATVRMID, D.SATWRMID, D.SAT_AVG, D.SAT_AVG_ALL, E.NPT4_PUB, E.NPT4_PRIV, E.NPT45_PUB, E.NPT45_PRIV
FROM dbo.Institution AS A
INNER JOIN dbo.Field_Study_Earnings AS B
ON A.UNITID = B.UNITID
INNER JOIN dbo.University_Year AS C
ON A.UNITID = C.UNITID
INNER JOIN dbo.SAT_ACT AS D
ON A.UNITID = D.UNITID
INNER JOIN dbo.Cost AS E
ON A.UNITID = E.UNITID
WHERE A.STABBR = 'FL' AND C.School_Year = '2018_19' AND D.School_Year = '2018_19' AND E.School_Year = '2018_19' AND B.CREDDESC LIKE 'Bachel%' AND B.CIPDESC LIKE '%Nurs%'
ORDER BY B.MD_EARN_WNE DESC
